services:
  postgres:
    container_name: "postgres"
    image: postgres:17-alpine3.22
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=pso
      - POSTGRES_PASSWORD=UI3omP5qpxO5VKN
      - POSTGRES_DB=pso