services:
  app:
    container_name: "app"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENV: ${ENV}
        DB_HOST: ${DB_HOST}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
        DB_NAME: ${DB_NAME}
        DB_PORT: ${DB_PORT}
        JWT_SECRET: ${JWT_SECRET}
    volumes:
      - .:/app
    ports:
      - 8888:8888
    depends_on:
      - postgres
    networks:
      - app-network

  nginx:
    container_name: "nginx"
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

  postgres:
    container_name: "postgres"
    hostname: postgres
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=pso
      - POSTGRES_PASSWORD=pso
      - POSTGRES_DB=pso
    networks:
      - app-network

volumes:
  app-data:

networks:
  app-network:
    driver: bridge